version: '3.4'

services:
  forumapi:
    image: ${DOCKER_REGISTRY-}forumapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqldata
 
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - SA_PASSWORD=2Secure*Password2
        - ACCEPT_EULA=Y
    ports:
        - "5440:1433"